package constant

const (
	RK_MSG_SEQ_ID                        = "MSG:SEQ_ID:"
	RK_SYNC_USER_ACCESS_TOKEN_SESSION_ID = "USER:ACCESS_TOKEN_SESSION_ID:"
	RK_SYNC_USER_ACCESS_TOKEN            = "USER:ACCESS_TOKEN:"
)
