CREATE TABLE `vip_users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uid` bigint unsigned NOT NULL COMMENT '用户ID 系统生成',
  `lark_id` varchar(32) NOT NULL DEFAULT '' COMMENT '账户ID 用户设置',
  `udid` varchar(40) NOT NULL DEFAULT '' COMMENT '注册设备唯一标识',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '用户状态',
  `nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '昵称',
  `firstname` varchar(32) NOT NULL DEFAULT '' COMMENT 'firstname',
  `lastname` varchar(32) NOT NULL DEFAULT '' COMMENT 'lastname',
  `gender` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '性别',
  `birth_ts` bigint NOT NULL DEFAULT '0' COMMENT '生日',
  `email` varchar(64) NOT NULL DEFAULT '' COMMENT 'Email',
  `mobile` varchar(32) NOT NULL DEFAULT '' COMMENT '手机号',
  `reg_platform` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '注册平台',
  `city_id` int NOT NULL DEFAULT '0' COMMENT '城市ID',
  `avatar` varchar(160) NOT NULL DEFAULT '' COMMENT '小图 72*72',
  `created_ts` bigint NOT NULL DEFAULT '0',
  `updated_ts` bigint NOT NULL DEFAULT '0',
  `deleted_ts` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_uid` (`uid`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_gender` (`gender`),
  KEY `idx_cityId` (`city_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;